### ISSUE TITLE
Question: Is wasmtime support?

### ISSUE THREAD

**Issue by dipankardas011** [KWasm/kwasm-operator#184]
How is it supported?
- how can I utilize it?
- what version of wasmtime it uses?
- as running a server and commandline app in wasmtime are different
commandline it is `wasmtime run ...`
server it is `wasmtime serve ...`

> Ig only create a instance of RuntimeClass with wasmtime might do

> Happy to correct myself ;)

**Comment by dipankardas011** [comment]
Yes I was able to find that containerd is already configured with wasmtime
https://github.com/KWasm/kwasm-node-installer/blob/main/script/installer.sh

**Comment by dipankardas011** [comment]
So are their any example workload for me to look how much different is it from wasmedge?

**Comment by 0xE282B0** [comment]
Hi @dipankardas011,
This project is just an installer for runwasi based runtimes.
You can find a demo app here: https://github.com/containerd/runwasi/tree/main/crates/wasi-demo-app
If you are looking for support the runwasi channel of the CNCF Slack is a great starting point 😊
https://cloud-native.slack.com/archives/C04LTPB6Z0V

**Comment by dipankardas011** [comment]
Okay will give it a try
Thanks @0xE282B0
