### ISSUE TITLE
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "crun" is configured

### ISSUE THREAD

**Issue by vincent0426** [KWasm/kwasm-operator#45]
Hi, I've followed the step in the Example section. However, I get the following error when I describe the pod since it's keep in the ContainerCreating state. How can I fix it? Thanks!

`wasi-demo   0/1     ContainerCreating   0          88s`

`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "crun" is configured`

# Create cluster
kind create cluster --config examples/kind/cluster.yaml
# Add helm repo
helm repo add kwasm http://kwasm.sh/kwasm-operator/
# Install operator
helm install -n kwasm --create-namespace kwasm-operator kwasm/kwasm-operator
# Annotate single node
kubectl annotate node kind-worker2 kwasm.sh/kwasm-node=true
# Run example
kubectl apply -f examples/kind/runtimeclass.yaml
kubectl apply -f examples/kind/pod.yaml

**Comment by 0xE282B0** [comment]
Oh no, it looks like I missed to update the example 🫣. Wait a minute.

**Comment by 0xE282B0** [comment]
@vincent0426  Could you try again?

**Comment by vincent0426** [comment]
Hi @0xE282B0, thanks. I can see the log of the pod as `File content is This is in a file ` at the end.
