### ISSUE TITLE
Vote for Operator Name

### ISSUE THREAD

**Issue by voigt** [KWasm/kwasm-operator#80]
We are building an operator that installs, updates and deletes application runtimes on Kubernetes nodes. This means we are not limited to WebAssembly runtimes, as was the case with its predecessor KWasm. We could install any runtime environment such as [Kata](https://katacontainers.io/), [https://bun.sh/](Bun) or similar.

The [original idea](https://hackmd.io/TwC8Fc8wTCKdoWlgNOqTgA) references the Operator as **containerd-shim-lifecylce-operator**. While we are focusing on contained shims for now, there is a possible demand for alternative container runtimes (such as CRI-O) and no technical reason not to support those.

With this issue I'd like to collect ideas and eventually vote on a proposal. Once we have settled on a name, we will make sure to rename the project as well as identifiers in the code accordingly.

**Ideas:**

* Kubernetes Runtime Lifecycle Manager
* RuntimeClass Manager

**Comment by flavio** [comment]
Both are fine, but I have a small preference for "RuntimeClass Manager"

**Comment by 0xE282B0** [comment]
For me, the main task is not to manage the RuntimeClass, but to set up the runtime. The RuntimeClass is just the tip of the iceberg, but since the user will mainly interact with the RuntimeClass, I can agree with this name. To stay in the picture, it is the visible part of the iceberg. 😉
